name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-format:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        name: Check out repository
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        name: Set up Node.js
        with:
          node-version: 22
          cache: npm
      - run: npm ci
        name: Install dependencies
      - run: npm run format:check
        name: Check code formatting
      - run: npm run lint
        name: Lint code

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        name: Check out repository
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        name: Set up Node.js
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
        name: Install dependencies
      - run: npm run test
        name: Run tests
